#My First Workflow

name: workflow1
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: |
          echo "hello from Asyraf"
          sleep 5
      - name: step2 for testing
        run: |
          cat /etc/os-release
          sleep 5
          hostname
## Name is not important in a step
      - run: uname -a
      
